// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {type: 'doc', id: 'intro', label: 'Introduction'},
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {type: 'doc', id: 'getting-started/quick-start', label: 'Quick Start'},
        {type: 'doc', id: 'getting-started/architecture', label: 'Architecture'},
        {type: 'doc', id: 'getting-started/concepts', label: 'Concepts'},
        {type: 'doc', id: 'getting-started/constraints', label: 'Validation Constraints'},
        {type: 'doc', id: 'getting-started/lifecycle', label: 'Service Lifecycle'},
        {type: 'doc', id: 'getting-started/server-start', label: 'Start Server'},
        {type: 'doc', id: 'getting-started/runtime-capabilities', label: 'Runtime Capabilities'},
        {type: 'doc', id: 'getting-started/database', label: 'Database'},
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        {type: 'doc', id: 'core-concepts/validation-model', label: 'Validation Model'},
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {type: 'doc', id: 'reference/reference-overview', label: 'Reference Overview'},
        {type: 'doc', id: 'reference/apistry-cli', label: 'CLI Reference'},
        {type: 'doc', id: 'reference/openapi-design', label: 'OpenAPI Contract Rules'},
        {type: 'doc', id: 'reference/openapi-design-merged', label: 'OpenAPI Contract Rules Merged'},
        {type: 'doc', id: 'reference/api-semantics', label: 'API Semantics'},
        {
          type: 'category',
          label: 'Query Filters',
          items: [
            {type: 'doc', id: 'reference/query-filters', label: 'Basics'},
            {type: 'doc', id: 'reference/defining-filters', label: 'Defining'},
          ],
        },
        {type: 'doc', id: 'reference/field-context-semantics', label: 'Field & Context Semantics'},
        {type: 'doc', id: 'reference/error-codes-and-status-mapping', label: 'Error Codes & Status Mapping'},
        {type: 'doc', id: 'reference/extensions', label: 'Extensions'},
        {type: 'doc', id: 'reference/system-endpoints', label: 'System Endpoints'},
        {type: 'doc', id: 'reference/etl', label: 'ETL'},
        {type: 'doc', id: 'reference/validation-reference', label: 'Validation Reference'},
        {
          type: 'category',
          label: 'Validations',
          items: [
              { type: 'autogenerated', dirName: 'reference/validations' }
            ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      collapsed: true,
      items: [
        { type: 'doc', id: 'demos/api-index', label: 'APIstry Demos' },
        { type: 'doc', id: 'demos/books-v1', label: 'Books API v1' },
        { type: 'doc', id: 'demos/cars-v1', label: 'Cars API v1' },
        { type: 'doc', id: 'demos/harry-potter-v1', label: 'Harry Potter API v1' },
        { type: 'doc', id: 'demos/notes-v1', label: 'Notes API v1' },
        { type: 'doc', id: 'demos/swapi-v1', label: 'Star Wars API v1' },
        { type: 'doc', id: 'demos/swapi-v2', label: 'Star Wars API v2' },
        { type: 'doc', id: 'demos/videos-v1', label: 'Videos API v1' },
      ],
    },
  ],
};

export default sidebars;
