openapi: 3.0.3
info:
  title: Rminders
  description: |
    API for managing and searching personal reminders including notes, preferences and tasks.
  version: v1
  contact:
    email: API-Gov-Team@gmail.com
    name: acme API Gov Team
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.acme.com/terms/
servers:
  - url: https://myserver.amazonaws.com
security:
  - bearerAuth: []
paths:
  /v1/notes:
    get:
      tags:
        - Notes
      summary: List user notes
      description: List user notes
      operationId: getNotes
      parameters:
        - $ref: '#/components/parameters/NoteTypeQueryOptional'
        - $ref: '#/components/parameters/NoteIdsQueryOptional'
        - $ref: '#/components/parameters/LimitQueryOptional'
        - $ref: '#/components/parameters/OffsetQueryOptional'
        - $ref: '#/components/parameters/OrderQueryOptional'
        - $ref: '#/components/parameters/XRequestId'
        - $ref: '#/components/parameters/XCorrelationId'
      responses:
        '200':
          description: A list of notes The response also includes a Content-Range header in the format 'items start-end/total', which provides the total record count.
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Notes
      description: Create multiple note records
      summary: Create notes in bulk
      operationId: createNotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Note'
              minItems: 1
              maxItems: 1000
      responses:
        '201':
          description: Notes created successfully in bulk
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/InternalServerError'
      parameters:
        - $ref: '#/components/parameters/XRequestId'
        - $ref: '#/components/parameters/XCorrelationId'
    patch:
      tags:
        - Notes
      description: Update multiple notes in your personal library. Only need to provide those fields that need to be updated. NoteType valid values are 'UpdatePreference', 'UpdateSimple', 'UpdateTask'.
      summary: Update notes
      operationId: updateNotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Note'
              minItems: 1
              maxItems: 1000
      responses:
        '200':
          description: Updated successfully
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/InternalServerError'
      parameters:
        - $ref: '#/components/parameters/XRequestId'
        - $ref: '#/components/parameters/XCorrelationId'
    delete:
      tags:
        - Notes
      description: Remove a user note from your settings
      summary: Delete notes
      operationId: deleteNotes
      parameters:
        - $ref: '#/components/parameters/NoteTypeQueryOptional'
        - $ref: '#/components/parameters/CategoryQueryOptional'
        - $ref: '#/components/parameters/NoteIdsQueryOptional'
        - $ref: '#/components/parameters/NoteIdQueryOptional'
        - $ref: '#/components/parameters/DueDateTimeQueryOptional'
        - $ref: '#/components/parameters/XRequestId'
        - $ref: '#/components/parameters/XCorrelationId'
      responses:
        '200':
          description: A list of notes The response also includes a Content-Range header in the format 'items start-end/total', which provides the total record count.
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          description: Too Many Requests
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    NoteTypeQueryOptional:
      description: Resource type
      name: noteType
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/NoteType'
    NoteIdsQueryOptional:
      description: Unique identifier for the note.
      name: noteIds
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          format: uuid
    NoteIdQueryOptional:
      description: Unique identifier for the note.
      name: noteId
      in: query
      required: false
      schema:
        type: string
        format: uuid
    DueDateTimeQueryOptional:
      description: Due date for the reminder (ISO 8601 format). Only applicable for tasks note.
      name: dueDateTime
      in: query
      required: false
      schema:
        type: string
        pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
    LimitQueryOptional:
      name: limit
      in: query
      description: Maximum number of items to return.
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 2000
    OffsetQueryOptional:
      name: offset
      in: query
      description: Number of items to skip before starting to collect the result set.
      required: false
      schema:
        type: integer
        minimum: 0
        maximum: 1000000
    OrderQueryOptional:
      name: order
      in: query
      description: Sort order for the results (e.g., order=title.asc).
      required: false
      schema:
        type: string
        pattern: ^[A-Za-z0-9_]+\.(asc|desc)$
    CategoryQueryOptional:
      name: category
      in: query
      description: Filter by category (supports wildcard and partial matches).
      required: false
      schema:
        type: string
        pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        minLength: 1
        maxLength: 40
    XRequestId:
      in: header
      name: X-Request-Id
      description: Represents a unique request
      schema:
        type: string
        format: uuid
      required: false
    XCorrelationId:
      in: header
      name: X-Correlation-Id
      description: Serves as a session id for multi-step workflows
      schema:
        type: string
        format: uuid
      required: false
  schemas:
    ContentRange:
      description: The content range of the response
      type: string
      example: items 0-24/100
    Error:
      type: object
      properties:
        code:
          description: Error Code
          type: integer
          minimum: 10000
          maximum: 99999
        message:
          type: string
          description: Error message from service
    ErrorItem:
      allOf:
        - $ref: '#/components/schemas/Error'
      type: object
      properties:
        objectName:
          description: Name of the object containing the field that is in error
          type: string
        field:
          description: Name of the field in error
          type: string
        rejectedValue:
          description: Value that caused the error
          type: string
    Note:
      oneOf:
        - $ref: '#/components/schemas/SimpleNote'
        - $ref: '#/components/schemas/Preference'
        - $ref: '#/components/schemas/Task'
      discriminator:
        propertyName: noteType
    NoteId:
      description: Unique noteIdentifier for this resource
      type: string
      format: uuid
      x-query: optional
      x-primary-key: true
      x-query-pattern: ^(eq\.|neq\.)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$|^isNull$
    NoteType:
      description: The type of resource this is
      type: string
      enum:
        - Simple
        - Preference
        - Task
    Notes:
      type: object
      readOnly: true
      properties:
        contentRange:
          $ref: '#/components/schemas/ContentRange'
        results:
          description: The list of resources
          type: array
          items:
            $ref: '#/components/schemas/Note'
          minItems: 0
          maxItems: 1000
    Preference:
      description: A user preference or configuration setting
      type: object
      x-context:
        required:
          post:
            - category
            - name
            - value
          put:
            - category
            - name
            - value
          delete:
            - noteId
          patch:
            - noteId
        prohibited:
          post:
            - noteId
          put:
            - noteId
      required:
        - noteType
      properties:
        noteId:
          $ref: '#/components/schemas/NoteId'
        noteType:
          type: string
          enum:
            - Preference
          x-query: required
        category:
          description: The category or group this preference belongs to
          type: string
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?-]+$
          minLength: 1
          maxLength: 40
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        name:
          description: The name of the preference setting
          type: string
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?-]+$
          minLength: 1
          maxLength: 40
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        value:
          description: The new value for this preference
          type: string
          minLength: 1
          maxLength: 200
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.)[A-Za-z0-9._,+:'|&@\s()#!?-]+$|^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$|^isNull$
        isPii:
          description: Whether this preference contains personally noteIdentifiable information
          type: boolean
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.)(true|false)$|^(true|false)$|^isNull$
        expiresAtDateTime:
          description: When this preference should expire (if applicable)
          type: string
          format: date-time
          x-query: optional
          x-query-pattern: ^(gt\.|lt\.|gte\.|lte\.|eq\.|neq\.)[0-9T:\-Z]+$|^[0-9T:\-Z]+$|^isNull$
    SimpleNote:
      description: A user note or configuration setting
      type: object
      x-context:
        required:
          post:
            - category
            - subject
            - note
          put:
            - category
            - subject
            - note
          delete:
            - noteId
          patch:
            - noteId
        prohibited:
          post:
            - noteId
          put:
            - noteId
      required:
        - noteType
      properties:
        noteId:
          $ref: '#/components/schemas/NoteId'
        noteType:
          type: string
          enum:
            - Simple
          x-query: required
        category:
          description: The category or group this note belongs to
          type: string
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?-]+$
          minLength: 1
          maxLength: 40
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        subject:
          description: The name of the note setting
          type: string
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?-]+$
          minLength: 1
          maxLength: 40
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        note:
          description: The new value for this note
          type: string
          pattern: ^[A-Za-z0-9._,+:;'|→/#%$&@\s()#!?*-]+$
          minLength: 1
          maxLength: 500
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:;'|→/#%$&@\s()#!?*-]+$
    Task:
      description: List of tasks - can be added to manually by user or is populated by pulling the calendar events.
      type: object
      x-context:
        required:
          post:
            - noteType
            - dueDateTime
            - title
          put:
            - noteId
            - noteType
            - dueDateTime
            - title
          delete:
            - noteId
          patch:
            - noteId
        prohibited:
          post:
            - noteId
      required:
        - noteType
      properties:
        noteId:
          $ref: '#/components/schemas/NoteId'
        noteType:
          type: string
          enum:
            - Task
          x-query: required
        category:
          description: The category
          type: string
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?-]+$
          maxLength: 100
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        providerId:
          description: External provider noteIdentifier
          type: string
        providerTaskListId:
          description: External provider task list ID
          type: string
        parentId:
          description: Parent task UUID for subtasks
          type: string
          format: uuid
          nullable: true
          x-query: optional
        dueDateTime:
          description: The due date and time for the task
          type: string
          format: date-time
          nullable: true
          x-query: optional
        completed:
          description: Whether the task is completed
          type: boolean
          default: false
          x-query: optional
        title:
          description: The title of the task
          type: string
          maxLength: 255
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        course:
          description: The course or project this task is associated with
          type: string
          maxLength: 255
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        calendarSource:
          description: which calendar this task was sourced from (if any)
          type: string
          maxLength: 255
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        notes:
          description: Additional notes for the task
          type: string
          maxLength: 500
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
        url:
          description: The URL associated with the task
          type: string
          maxLength: 500
          x-query: optional
  headers:
    ContentRange:
      description: Total count of items matching the filter criteria
      schema:
        type: string
        example: 0-700/*
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ErrorItem'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ErrorItem'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
externalDocs:
  description: Find out more about acme API Products
  url: https://developer.acme.com
