openapi: 3.0.3
info:
  title: Videos
  description: Videos
  termsOfService: https://developer.acme.com/terms/
  contact:
    name: acme API Gov Team
    email: API-Gov-Team@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
externalDocs:
  description: Find out more about acme API Products
  url: https://developer.acme.com
servers:
  - url: https://localhost:3000
security:
  - bearerAuth: []
paths:
  /v1/videos:
    get:
      tags:
        - Videos
      summary: List videos
      description: List videos
      operationId: getVideos
      parameters:
        - name: ids
          in: query
          description: Unique identifier for the video.
          required: false
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              format: uuid
        - name: limit
          in: query
          description: Maximum number of items to return.
          required: false
          style: form
          explode: true
          schema:
            maximum: 2000
            minimum: 1
            type: integer
        - name: offset
          in: query
          description: Number of items to skip before starting to collect the result set.
          required: false
          style: form
          explode: true
          schema:
            maximum: 1000000
            minimum: 0
            type: integer
        - name: order
          in: query
          description: Sort order for the results (e.g., order=title.asc).
          required: false
          style: form
          explode: true
          schema:
            pattern: ^[A-Za-z0-9_]+\.(asc|desc)$
            type: string
      responses:
        '200':
          description: >-
            A list of videos The response also includes a Content-Range header
            in the format 'items start-end/total', which provides the total
            record count.
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Videos'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Videos
      summary: Create videos in bulk
      description: Create multiple video records
      operationId: createVideos
      requestBody:
        content:
          application/json:
            schema:
              maxItems: 1000
              minItems: 1
              type: array
              items:
                $ref: '#/components/schemas/Video'
        required: true
      responses:
        '201':
          description: Videos created successfully in bulk
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Videos'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Videos
      summary: Delete videos
      description: Remove a video
      operationId: deleteVideos
      parameters:
        - name: category
          in: query
          description: Filter by category (supports wildcard and partial matches).
          required: false
          style: form
          explode: true
          schema:
            maxLength: 40
            minLength: 1
            pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
            type: string
        - name: ids
          in: query
          description: Unique identifier for the video.
          required: false
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              format: uuid
        - name: id
          in: query
          description: Unique identifier for the video.
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: uuid
        - name: dueDateTime
          in: query
          description: >-
            Due date for the video (ISO 8601 format). Only applicable for tasks
            video.
          required: false
          style: form
          explode: true
          schema:
            pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*-]+$
            type: string
      responses:
        '200':
          description: >-
            A list of videos The response also includes a Content-Range header
            in the format 'items start-end/total', which provides the total
            record count.
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Videos'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Videos
      summary: Update videos
      description: >-
        Update multiple videos in your personal library. Only need to provide
        those fields that need to be updated.
      operationId: updateVideos
      requestBody:
        content:
          application/json:
            schema:
              maxItems: 1000
              minItems: 1
              type: array
              items:
                $ref: '#/components/schemas/Video'
        required: true
      responses:
        '200':
          description: Updated successfully
          headers:
            Content-Range:
              $ref: '#/components/headers/ContentRange'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Videos'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ContentRange:
      type: string
      description: The content range of the response
      example: items 0-24/100
    Error:
      type: object
      properties:
        code:
          maximum: 99999
          minimum: 10000
          type: integer
          description: Error Code
        message:
          type: string
          description: Error message from service
    ErrorItem:
      type: object
      properties:
        objectName:
          type: string
          description: Name of the object containing the field that is in error
        field:
          type: string
          description: Name of the field in error
        rejectedValue:
          type: string
          description: Value that caused the error
        code:
          maximum: 99999
          minimum: 10000
          type: integer
          description: Error Code
        message:
          type: string
          description: Error message from service
    Id:
      type: string
      description: Unique identifier for this resource
      format: uuid
      x-query: optional
      x-primary-key: true
      x-query-pattern: >-
        ^(eq\.|neq\.)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$|^isNull$
    MovieRatings:
      type: string
      description: Content ratings and advisory information
      enum:
        - TV-Y7
        - NR
        - G
        - TV-Y
        - Approved
        - PG
        - TV-G
        - TV-14
        - TV-PG
        - PG-13
        - Not Rated
        - R
    Video:
      required:
        - resourceType
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        resourceType:
          type: string
          enum:
            - Video
          x-query: required
        providerSource:
          type: string
          description: The service or platform where this video was obtained
          enum:
            - plex
            - netflix
            - primevideo
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.)(plex|netflix|primevideo)$|^isNull$
        addedAtDateTime:
          type: string
          description: When this video was added to your library from the original source
          format: date-time
          readOnly: true
          x-query: optional
          x-query-pattern: >-
            ^(gt\.|lt\.|gte\.|lte\.|eq\.|neq\.)[0-9T:\-Z]+$|^[0-9T:\-Z]+$|^isNull$
        lastPlayedAtDateTime:
          type: string
          description: When you last watched this video
          format: date-time
          x-query: optional
          x-query-pattern: >-
            ^(gt\.|lt\.|gte\.|lte\.|eq\.|neq\.)[0-9T:\-Z]+$|^[0-9T:\-Z]+$|^isNull$
        lastPositionMins:
          minimum: 0
          type: integer
          description: Your current viewing position in minutes
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.|gt\.|lt\.|gte\.|lte\.)[0-9]+$|^[0-9]+$|^isNull$
        userRating:
          maximum: 10
          minimum: 0
          type: integer
          description: Your personal rating of this video (0-10 scale)
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.|gt\.|lt\.|gte\.|lte\.)[0-9]+$|^[0-9]+$|^isNull$
        mediaType:
          type: string
          description: The type of content (movie or tv)
          enum:
            - movie
            - tv
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.)(movie|tv)$|^isNull$
        tmdbId:
          maxLength: 10
          minLength: 1
          pattern: ^[0-9]+$
          type: string
          description: The Movie Database identifier
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.)[0-9]+$|^[0-9*]+$|^isNull$
        imdbId:
          maxLength: 10
          minLength: 9
          pattern: ^tt[0-9]+$
          type: string
          description: Internet Movie Database identifier
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.)tt[0-9]+$|^tt[0-9*]+$|^isNull$
        title:
          maxLength: 150
          minLength: 1
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?/-]+$
          type: string
          description: The title of the video
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*/-]+$
        movieRatings:
          $ref: '#/components/schemas/MovieRatings'
        seriesName:
          maxLength: 150
          minLength: 1
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?/-]+$
          type: string
          description: Name of the series this video belongs to (for TV shows)
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*/-]+$
        episodeTitle:
          maxLength: 150
          minLength: 1
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?/-]+$
          type: string
          description: Title of the specific episode (for TV shows)
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*/-]+$
        season:
          maxLength: 50
          minLength: 1
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?/-]+$
          type: string
          description: Season identifier (for TV shows)
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*/-]+$
        releaseYear:
          type: integer
          description: Year the video was released
          x-query: optional
          x-query-pattern: ^(eq\.|neq\.|gt\.|lt\.|gte\.|lte\.)[0-9]+$|^[0-9]+$|^isNull$
        releaseDate:
          type: string
          description: Official release date of the video
          format: date
          x-query: optional
          x-query-pattern: >-
            ^(gt\.|lt\.|gte\.|lte\.|eq\.|neq\.)[0-9]{4}-[0-9]{2}-[0-9]{2}$|^[0-9]{4}-[0-9]{2}-[0-9]{2}$|^isNull$
        genres:
          maxLength: 100
          minLength: 1
          pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?/-]+$
          type: string
          description: Comma-separated list of genres
          x-query: optional
          x-query-pattern: ^[A-Za-z0-9._,+:'|&@\s()#!?*/-]+$
      description: A video in your personal library (movie, TV show, etc.)
      x-context:
        required:
          post:
            - title
            - mediaType
          put:
            - title
            - mediaType
          delete:
            - id
          patch:
            - id
        prohibited:
          post:
            - id
          put:
            - id
    Videos:
      type: object
      properties:
        contentRange:
          $ref: '#/components/schemas/ContentRange'
        results:
          maxItems: 1000
          minItems: 0
          type: array
          description: The list of videos
          items:
            $ref: '#/components/schemas/Video'
      readOnly: true
  headers:
    ContentRange:
      description: Total count of items matching the filter criteria
      schema:
        type: string
        example: 0-700/*
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
