openapi: 3.0.3
info:
  title: Personal Assistant
  description: >
    API for managing and searching personal media collections including books,
    videos, preferences and notes resources.

    When updating or creating resources, ONLY provide the fields you want to
    change and DO NOT send read-only fields.

    Query Filters are provided for all children resources, but if a param is
    provided that is not valid for a given resource

    it will be ignored.

      ### Query Operators

      The API supports the following operators for filtering:

      | Operator      | Description                                                                 | Example                                      |
      |---------------|-----------------------------------------------------------------------------|----------------------------------------------|
      | `eq.<value>`  | Equals the specified value.                                                  | `"userRating": "eq.5"` → books with rating 5 |
      | `neq.<value>` | Not equal to the specified value.                                           | `"author": "neq.Unknown"`                    |
      | `gt.<number>` | Greater than (for numeric values).                                          | `"userRating": "gt.7"`                       |
      | `lt.<number>` | Less than (for numeric values).                                             | `"userRating": "lt.3"`                       |
      | `gte.<number>`| Greater than or equal to.                                                   | `"userRating": "gte.8"`                      |
      | `lte.<number>`| Less than or equal to.                                                      | `"userRating": "lte.2"`                      |
      | `isNull`      | Returns items where the field is missing, empty, or null.                   | `"isbnId": "isNull"` → books without ISBNs   |
      | `*` (wildcard)| Matches partial values (supports leading/trailing wildcards).                | `"title": "*Survivor*"` → titles containing “Survivor” |

      ### Examples

      - **Books without an ISBN**
        ```json
        { "isbnId": "isNull" }
        ```

      - **Audiobooks with no narrator listed**
        ```json
        { "narrator": "isNull" }
        ```

      - **Titles missing genre information**
        ```json
        { "genres": "isNull" }
        ```
  termsOfService: https://developer.acme.com/terms/
  contact:
    name: acme API Gov Team
    email: API-Gov-Team@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
externalDocs:
  description: Find out more about acme API Products
  url: https://developer.acme.com
servers:
  - url: https://1wz48u09w6.execute-api.us-west-1.amazonaws.com
security:
  - bearerAuth: []
paths:
  /v1/{proxy+}:
    x-amazon-apigateway-any-method:
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:447315180786:function:api-gateway/invocations
        httpMethod: POST
        type: aws_proxy
  /v1/health:
    get:
      tags:
        - Health
      summary: Health check endpoint
      description: Returns the health status of the Personal Assistant API.
      operationId: getHealth
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/schemas:
    get:
      tags:
        - Schemas
      summary: Get resource schemas
      description: Returns the health status of the Personal Assistant API.
      operationId: getSchemas
      parameters:
        - name: resourceType
          in: query
          description: Resource type
          required: false
          style: form
          explode: true
          schema:
            $ref: '#/components/schemas/ResourceType'
        - name: method
          in: query
          description: Resource type
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - query
              - post
              - put
              - patch
              - delete
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                maxItems: 1000
                minItems: 0
                type: array
                items:
                  $ref: '#/components/schemas/Schema'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Unauthorized search request.
        '403':
          description: Forbidden - The request is understood but access is not permitted.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorItem'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          maximum: 99999
          minimum: 10000
          type: integer
          description: Error Code
        message:
          type: string
          description: Error message from service
    ErrorItem:
      type: object
      properties:
        objectName:
          type: string
          description: Name of the object containing the field that is in error
        field:
          type: string
          description: Name of the field in error
        rejectedValue:
          type: string
          description: Value that caused the error
        code:
          maximum: 99999
          minimum: 10000
          type: integer
          description: Error Code
        message:
          type: string
          description: Error message from service
    ResourceType:
      type: string
      description: The type of resource this is
      enum:
        - Book
        - Calendar
        - Note
        - Preference
        - Task
        - Video
    Schema:
      type: object
      properties:
        resourceType:
          type: string
        propertyName:
          type: string
        post:
          type: string
        put:
          type: string
        patch:
          type: string
        delete:
          type: string
        query:
          type: string
        queryPattern:
          type: string
        primaryKey:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
