# Basic container config. The Docker image includes this file at
# /home/node/site/config.yml.

server:
  host: 0.0.0.0
  port: 3000
  serviceName: APIstry
  serviceDescription: >
    APIstry provides functional APIs directly from OpenAPI specifications
    without writing any code.
  swaggerUiEnabled: true

contracts:
  path: /home/node/site/contracts

database:
  connection: sqlite:///home/node/site/sqlite.db

logging:
  level: info
  pretty: false
  redact:
    - req.headers.authorization
    - req.headers.cookie

cors:
  enabled: true
  origins: true
